# Generated by Django 4.2.11 on 2024-09-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ki', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='bot_nr',
        ),
        migrations.RemoveField(
            model_name='botaccess',
            name='bot_nr',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='bot_nr',
        ),
        migrations.RemoveField(
            model_name='promptchoice',
            name='bot_nr',
        ),
        migrations.RemoveField(
            model_name='subjectaccess',
            name='bot_nr',
        ),
    ]
