# Generated by Django 4.2.11 on 2024-09-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ki', '0002_remove_bot_bot_nr_remove_botaccess_bot_nr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='img_bot',
            field=models.BooleanField(default=False),
        ),
    ]
