# Generated by Django 4.2.11 on 2024-09-18 07:11

from django.db import migrations

def make_img_bot(apps, schema_editor):
    Bot = apps.get_model('ki', 'Bot')
    Bot.objects.create(
        title='Bilde­generator',
        img_bot=True,
        model='dall-e-3',
        temperature=0.7,
        prompt_visibility=True,
        library=True,
        owner='',
        allow_distribution=True,
        mandatory=True,
        bot_info='Dette er en bot som lager et bilde basert på en tekstbeskrivelse.',
        tag_cat_1=0,
        tag_cat_2=0,
        tag_cat_3=0
    )
    

class Migration(migrations.Migration):

    dependencies = [
        ('ki', '0003_bot_img_bot'),
    ]

    operations = [
        migrations.RunPython(make_img_bot),
    ]
