# Generated by Django 4.2.11 on 2024-10-09 07:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ki', '0005_uselog_logschool'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "ALTER TABLE bot CHANGE uuid uuid UUID;",
                "ALTER TABLE bot_access CHANGE bot_id bot_id UUID;",
                "ALTER TABLE favorite CHANGE bot_id bot_id UUID;",
                "ALTER TABLE prompt_choice CHANGE bot_id bot_id UUID;",
                "ALTER TABLE subject_access CHANGE bot_id bot_id UUID;",
                "ALTER TABLE use_log CHANGE bot_id bot_id UUID;",
            ),
            reverse_sql=(
                "ALTER TABLE bot CHANGE uuid uuid VARCHAR(36);",
                "ALTER TABLE bot_access CHANGE bot_id bot_id VARCHAR(36);",
                "ALTER TABLE favorite CHANGE bot_id bot_id VARCHAR(36);",
                "ALTER TABLE prompt_choice CHANGE bot_id bot_id VARCHAR(36);",
                "ALTER TABLE subject_access CHANGE bot_id bot_id VARCHAR(36);",
                "ALTER TABLE use_log CHANGE bot_id bot_id VARCHAR(36);",
            ),
        ),
    ]
