# Generated by Django 4.2.11 on 2024-10-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ki', '0006_tagcategory_remove_bot_tag_cat_1_and_more'),
    ]

    def update_image_attr(apps, schema_editor):
        Bot = apps.get_model('ki', 'Bot')
        for bot in Bot.objects.all():
            if bot.image == "bot2.svg":
                bot.avatar_scheme = "1,0,0,0,0,0,0"
            elif bot.image == "bot3.svg":
                bot.avatar_scheme = "2,0,0,0,0,0,0"
            elif bot.image == "bot4.svg":
                bot.avatar_scheme = "3,0,0,0,0,0,0"
            elif bot.image == "bot5.svg":
                bot.avatar_scheme = "4,0,0,0,0,0,0"
            else:
                bot.avatar_scheme = "0,0,0,0,0,0,0"
            bot.save()

    operations = [
        migrations.AddField(
            model_name='bot',
            name='avatar_scheme',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.RunPython(update_image_attr),
        migrations.RemoveField(
            model_name='bot',
            name='image',
        ),

    ]
