# Generated by Django 4.2.11 on 2024-12-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ki', '0007_bot_image_attr'),
    ]

    operations = [
        migrations.AddField(
            model_name='uselog',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='uselog',
            name='message_length',
            field=models.IntegerField(null=True),
        ),
    ]
