# Generated by Django 4.2.11 on 2024-12-03 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ki', '0007_bot_image_attr'),
    ]

    def populate_bot_model(apps, schema_editor):
        BotModel = apps.get_model('ki', 'BotModel')
        model = BotModel(
            deployment_id='gpt-4o-mini',
            provider='Azure',
            display_name='GPT-4o Mini', 
            model_description='', 
            filter='ki-filter-prod', 
            version='2024-07-18'
        )
        model.save()
        model = BotModel(
            deployment_id='gpt-4o',
            provider='Azure',
            display_name='GPT-4o', 
            model_description='', 
            filter='ki-filter-prod', 
            version='2024-08-06'
        )
        model.save()
        model = BotModel(
            deployment_id='dall-e-3',
            provider='Azure',
            display_name='DALL-E 3', 
            model_description='', 
            filter='ki-filter-prod', 
            version='3.0'
        )
        model.save()

    def update_bots(apps, schema_editor):
        Bot = apps.get_model('ki', 'Bot')
        BotModel = apps.get_model('ki', 'BotModel')
        for bot in Bot.objects.all():
            if bot.model == "gpt-4o-mini":
                bot.model_id = BotModel.objects.get(deployment_id='gpt-4o-mini')
            elif bot.model == "gpt-4o":
                bot.model_id = BotModel.objects.get(deployment_id='gpt-4o')
            elif bot.model == "dall-e-3":
                bot.model_id = BotModel.objects.get(deployment_id='dall-e-3')
            else:
                bot.model_id = None
            bot.save()

    operations = [
        migrations.CreateModel(
            name='BotModel',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('deployment_id', models.CharField(max_length=36, null=True)),
                ('provider', models.CharField(max_length=50)),
                ('model_url', models.CharField(max_length=500, null=True)),
                ('display_name', models.CharField(max_length=500, null=True)),
                ('model_description', models.TextField(null=True)),
                ('training_cutoff', models.CharField(max_length=200, null=True)),
                ('retirement', models.CharField(max_length=200, null=True)),
                ('filter', models.CharField(max_length=50, null=True)),
                ('version', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'bot_model',
            },
        ),
        migrations.RunPython(code=populate_bot_model, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name='bot',
            name='model_id',
            field=models.ForeignKey(db_column='model_id', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bots_id', to='ki.botmodel'),
        ),
        migrations.RunPython(code=update_bots, reverse_code=migrations.RunPython.noop),
    ]
