# Generated by Django 4.2.11 on 2025-01-08 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ki', '0008_botmodel_bot_model_id'),
        ('ki', '0008_uselog_level_alter_uselog_message_length'),
    ]

    operations = [
    ]
