# Generated by Django 4.2.11 on 2025-01-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ki', '0009_merge_20250108_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='model',
        ),
        migrations.AddField(
            model_name='bot',
            name='is_audio_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
