# Generated by Django 4.2.18 on 2025-02-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ki', '0010_remove_bot_model_bot_is_audio_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='uselog',
            name='interaction_type',
            field=models.CharField(choices=[('text', 'Text'), ('audio', 'Audio')], default='text', max_length=10),
        ),
    ]
