# Generated by Django 4.2.18 on 2025-02-26 15:28

from django.db import migrations, models
from datetime import timedelta


class Migration(migrations.Migration):

    def populate_valid_to(apps, schema_editor):
        SubjectAccess = apps.get_model('ki', 'SubjectAccess')
        for subject_access in SubjectAccess.objects.all():
            subject_access.valid_to = subject_access.created + timedelta(hours=24)
            subject_access.save()

    def add_setting_values(apps, schema_editor):
        Setting = apps.get_model('ki', 'Setting')
        Setting.objects.create(setting_key='default_lifespan', label='Standard levetid for tildeling (dager)', int_val=2, is_txt=False).save()
        Setting.objects.create(setting_key='max_lifespan', label='Maksimal levetid for tildeling (dager)', int_val=7, is_txt=False).save()

    def update_allow_distribution_for_personal_bots(apps, schema_editor):
        Bot = apps.get_model('ki', 'Bot')
        Bot.objects.filter(owner__isnull=False, library=False).update(allow_distribution=True)
 
    dependencies = [
        ('ki', '0011_uselog_interaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectaccess',
            name='valid_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='subjectaccess',
            name='valid_to',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(code=populate_valid_to, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='subjectaccess',
            name='valid_to',
            field=models.DateTimeField(),
        ),
        migrations.RunPython(code=add_setting_values, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(code=update_allow_distribution_for_personal_bots, reverse_code=migrations.RunPython.noop),

    ]
