# Generated by Django 4.2.20 on 2025-04-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    def set_weight(apps, schema_editor):
        TagLabel = apps.get_model('ki', 'TagLabel')
        for tag_label in TagLabel.objects.all():
            tag_label.tag_label_weight = tag_label.tag_label_order
            tag_label.save()

    dependencies = [
        ('ki', '0012_subjectaccess_valid_from_subjectaccess_valid_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='taglabel',
            name='tag_label_weight',
            field=models.IntegerField(null=True),
        ),
        migrations.RunPython(code=set_weight, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='taglabel',
            name='tag_label_weight',
            field=models.IntegerField(),
        ),
    ]
