# Generated by Django 4.2.20 on 2025-04-16 12:36

from django.db import migrations

settings_to_be_removed = [
    'allow_groups', 
    'lifespan', 
    'tag_categories',
    'allow_personal'
]
class Migration(migrations.Migration):

    def remove_settings(apps, schema_editor):
        Setting = apps.get_model('ki', 'Setting')
        for setting_key in settings_to_be_removed:
            Setting.objects.filter(setting_key=setting_key).delete()


    dependencies = [
        ('ki', '0013_taglabel_tag_label_weight_and_more'),
    ]

    operations = [
        migrations.RunPython(code=remove_settings, reverse_code=migrations.RunPython.noop),
    ]
