# Generated by Django 4.2.20 on 2025-04-28 06:54

from django.db import migrations


class Migration(migrations.Migration):

    def change_setting_key(apps, schema_editor):
        Setting = apps.get_model('ki', 'Setting')
        Setting.objects.filter(setting_key='view_filter').update(setting_key='is_bot_filtering_enabled')

    dependencies = [
        ('ki', '0014_auto_20250416_1436'),
    ]

    operations = [
        migrations.RunPython(code=change_setting_key, reverse_code=migrations.RunPython.noop),
    ]
