# Generated by Django 4.2.20 on 2025-05-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ki', '0015_auto_20250428_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='user_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
