# Generated by Django 4.2.20 on 2025-06-03 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ki', '0016_role_user_name_alter_bot_allow_distribution_and_more'),
    ]

    rebuild_foreign_keys = """
            ALTER TABLE `role` ADD `school_id` int NULL;
            UPDATE role JOIN school ON role.school = school.org_nr SET role.school_id = school.id WHERE role.school IS NOT NULL;
            ALTER TABLE role DROP COLUMN school;
            ALTER TABLE role ADD INDEX (school_id);
            ALTER TABLE school_access CHANGE school_id school_old VARCHAR(20);
            ALTER TABLE `school_access` ADD `school_id` int NULL;
            UPDATE school_access JOIN school ON school_access.school_old = school.org_nr SET school_access.school_id = school.id WHERE school_access.school_old IS NOT NULL;
            ALTER TABLE school_access DROP COLUMN school_old;
            ALTER TABLE school_access ADD INDEX (school_id);

            ALTER TABLE bot_access CHANGE school_id school_old VARCHAR(20);
            ALTER TABLE `bot_access` ADD `school_id` int NULL;
            ALTER TABLE bot_access DROP INDEX `bot_access_bot_id_school_id_978ac286_uniq`;
            UPDATE bot_access JOIN school ON bot_access.school_old = school.org_nr SET bot_access.school_id = school.id WHERE bot_access.school_old IS NOT NULL;
            ALTER TABLE bot_access DROP COLUMN school_old;
            ALTER TABLE bot_access ADD INDEX (school_id);

            ALTER TABLE log_school CHANGE log_id use_log_id INT;
        """

    operations = [

        migrations.AlterField(
            model_name='setting',
            name='setting_key',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='id',
            field=models.AutoField(primary_key=True),
        ),
        migrations.RenameField(
            model_name='bot',
            old_name='prompt_visibility',
            new_name='is_prompt_visible',
        ),
        migrations.RenameField(
            model_name='bot',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='bot',
            old_name='library',
            new_name='is_library_bot',
        ),
        migrations.RenameField(
            model_name='bot',
            old_name='allow_distribution',
            new_name='is_distribution_allowed',
        ),
        migrations.RenameField(
            model_name='bot',
            old_name='mandatory',
            new_name='is_mandatory',
        ),
        migrations.RenameField(
            model_name='bot',
            old_name='img_bot',
            new_name='is_img_bot',
        ),
        migrations.RenameField(
            model_name='botmodel',
            old_name='deployment_id',
            new_name='deployment_key',
        ),
        migrations.RenameField(
            model_name='botmodel',
            old_name='model_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='user_id',
            new_name='feide_user',
        ),
        migrations.AlterField(
            model_name='school',
            name='org_nr',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='school',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='school',
            old_name='school_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='school_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='botaccess',
            old_name='access_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='botlevel',
            old_name='level_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='schoolaccess',
            old_name='access_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='pagetext',
            old_name='page_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='pagetext',
            old_name='page_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='pagetext',
            old_name='page_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='pagetext',
            old_name='public',
            new_name='is_public',
        ),
        migrations.AlterField(
            model_name='role',
            name='user_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RenameField(
            model_name='role',
            old_name='user_id',
            new_name='feide_user',
        ),
        migrations.AddField(
            model_name='role',
            name='id',
            field=models.AutoField(primary_key=True),
        ),

        migrations.RenameField(
            model_name='tagcategory',
            old_name='category_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='tagcategory',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tagcategory',
            old_name='category_order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='taglabel',
            old_name='tag_label_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='taglabel',
            old_name='tag_label_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='taglabel',
            old_name='tag_label_weight',
            new_name='weight',
        ),
        migrations.RenameField(
            model_name='taglabel',
            old_name='tag_label_order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tag_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tag_value',
            new_name='value',
        ),
        migrations.RunSQL(rebuild_foreign_keys, migrations.RunSQL.noop),

        # migrations.AlterUniqueTogether(
        #     name='botaccess',
        #     unique_together=['bot', 'school'],
        # ),
    ]