# Generated by Django 4.2.20 on 2025-06-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ki', '0016_role_user_name_alter_bot_allow_distribution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('has_self_service', models.BooleanField(default=False)),
                ('valid_to', models.DateTimeField(null=True)),
                ('memberships', models.JSONField(default=dict, null=True)),
            ],
            options={
                'db_table': 'external_user',
            },
        ),
        migrations.AlterField(
            model_name='bot',
            name='allow_distribution',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subjectaccess',
            name='valid_to',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='taglabel',
            name='tag_label_weight',
            field=models.IntegerField(null=True),
        ),
    ]
