# Generated by Django 4.2.23 on 2025-08-21 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ki', '0017_localuser_alter_bot_allow_distribution_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='user_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='role',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
        migrations.RenameField(
            model_name='role',
            old_name='user_id',
            new_name='username',
        ),
        migrations.AddField(
            model_name='role',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='externaluser',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='externaluser',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='externaluser',
            name='valid_to',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
