# Generated by Django 4.2.20 on 2025-06-03 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ki', '0017_localuser_alter_bot_allow_distribution_and_more'),
    ]


    operations = [

        # Setting
        migrations.AlterField(
            model_name='setting',
            name='setting_key',
            field=models.CharField(max_length=50, unique=True),
        ),

        # School
        migrations.AlterField(
            # Remove the old foreign key constraint
            model_name='role',
            name='school',
            field=models.CharField(max_length=50, null=True, blank=True),
        ),
        migrations.AlterField(
            # Remove the old foreign key constraint
            model_name='schoolaccess',
            name='school_id',
            field=models.CharField(max_length=50, null=True, blank=True),
        ),
        migrations.AlterUniqueTogether(
            # Remove the old unique constraint
            name='botaccess',
            unique_together=set(),
        ),
        migrations.AlterField(
            # Remove the old foreign key constraint
            model_name='botaccess',
            name='school_id',
            field=models.CharField(max_length=50, null=True, blank=True),
        ),
        migrations.AlterField(
            # Remove the old primary index 
            model_name='school',
            name='org_nr',
            field=models.CharField(max_length=20, unique=True),
        ),

        # Role
        migrations.AlterField(
            # Remove the old primary index
            model_name='role',
            name='user_id',
            field=models.CharField(max_length=50, unique=True),
        ),

        # LogSchool
        migrations.AlterUniqueTogether(
            # Remove the old unique constraint
            name='logschool',
            unique_together=set(),
        ),
        migrations.AlterField(
            # Remove the old foreign key constraint
            model_name='logschool',
            name='log_id',
            field=models.CharField(max_length=50, null=True, blank=True),
        ),
        migrations.AlterField(
            # Remove the old foreign key constraint
            # Need to use the org_nr in the log table
            model_name='logschool',
            name='school_id',
            field=models.CharField(max_length=20, null=True, blank=True),
        ),

    ]