# Generated by Django 4.2.23 on 2025-09-01 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ki', '0018_rename_user_name_role_name_remove_role_user_id_and_more'),
    ]

    def insert_max_message_length(apps, schema_editor):
        Setting = apps.get_model('ki', 'Setting')
        setting_instance = Setting.objects.create(
            setting_key='max_message_length',
            label='Maks tekstlengde ved innliming',
            int_val=15000,
            is_txt=False
        )
        setting_instance.save()

    operations = [
        migrations.RunPython(insert_max_message_length),
    ]
