# Generated by Django 4.2.20 on 2025-06-03 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ki', '0019_alter_school_options_and_more'),
    ]

    operations = [


        # Role
        migrations.RemoveField(
            # Remove the old foreign key field
            model_name='role',
            name='school',
        ),
        migrations.RenameField(
            # Rename the temporary field to the new foreign key field
            model_name='role',
            old_name='school_temporary',
            new_name='school',
        ),

        migrations.AlterField(
            # Set the new foreign key field
            model_name='role',
            name='school',
            field=models.ForeignKey(
                to='ki.school',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='roles',
                null=True,
            ),
        ),

        # SchoolAccess
        migrations.RemoveField(
            # Remove the old foreign key field
            model_name='schoolaccess',
            name='school_id',
        ),
        migrations.RenameField(
            # Rename the temporary field to the new foreign key field
            model_name='schoolaccess',
            old_name='school_temporary',
            new_name='school',
        ),
        migrations.AlterField(
            # Set the new foreign key field
            model_name='schoolaccess',
            name='school',
            field=models.ForeignKey(
                to='ki.school',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='school_accesses',
                null=True,
            ),
        ),

        # BotAccess
        migrations.RemoveField(
            # Remove the old foreign key field
            model_name='botaccess',
            name='school_id',
        ),
        migrations.RenameField(
            # Rename the temporary field to the new foreign key field
            model_name='botaccess',
            old_name='school_temporary',
            new_name='school',
        ),
        migrations.AlterField(
            # Set the new foreign key field
            model_name='botaccess',
            name='school',
            field=models.ForeignKey(
                to='ki.school',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='bot_accesses',
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            # Set the new unique constraint
            name='botaccess',
            unique_together=['bot', 'school'],
        ),

        # LogSchool
        migrations.AlterField(
            # Set the new foreign key field
            model_name='logschool',
            name='use_log',
            field=models.ForeignKey(
                to='ki.uselog',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='schools',
                null=True,
            ),
        ),

    ]