# Generated by Django 4.2.24 on 2025-10-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ki', '0019_auto_20250901_1357'),
    ]

    def update_existing_pagetexts(apps, schema_editor):
        PageText = apps.get_model('ki', 'PageText')
        for pagetext in PageText.objects.all():
            pagetext.accessable_by = 'student' if pagetext.public else 'employee'
            pagetext.save()

    operations = [
        migrations.AddField(
            model_name='pagetext', name='accessable_by', field=models.CharField(
                choices=[('student', 'Student'),
                         ('employee', 'Employee'),
                         ('all', 'All')],
                default='all', max_length=10),),
        migrations.RunPython(update_existing_pagetexts, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(model_name='pagetext', name='public',),]
