# Generated by Django 4.2.25 on 2025-11-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ki', '0020_remove_pagetext_public_pagetext_accessable_by'),
    ]

    def insert_is_audio_enabled_for_all(apps, schema_editor):
        Setting = apps.get_model('ki', 'Setting')
        setting_instance = Setting.objects.create(
            setting_key='is_audio_enabled_for_all',
            label='Tale åpen for lærer',
            int_val=0,
            is_txt=False
        )
        setting_instance.save()

    operations = [
        migrations.RunPython(insert_is_audio_enabled_for_all),
    ]
