# Generated by Django 4.2.24 on 2025-10-20 14:07

from django.db import migrations
import ki.models


class Migration(migrations.Migration):

    dependencies = [
        ('ki', '0020_remove_pagetext_public_pagetext_accessable_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='title',
            field=ki.models.TruncatingCharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='choiceoption',
            name='label',
            field=ki.models.TruncatingCharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='externaluser',
            name='name',
            field=ki.models.TruncatingCharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pagetext',
            name='page_title',
            field=ki.models.TruncatingCharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='promptchoice',
            name='label',
            field=ki.models.TruncatingCharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=ki.models.TruncatingCharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='label',
            field=ki.models.TruncatingCharField(max_length=50),
        ),
    ]
