# Generated by Django 5.2.8 on 2026-01-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ki', '0021_auto_20251114_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetext',
            name='has_separate_menu',
            field=models.BooleanField(default=False),
        ),
    ]
