# Generated by Django 5.2.8 on 2026-02-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ki', '0022_pagetext_has_separate_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='reasoning_effort',
            field=models.CharField(choices=[('none', 'None'), ('minimal', 'Minimal'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='verbosity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='botmodel',
            name='is_reasoning_model',
            field=models.BooleanField(default=False),
        ),
    ]
