name: Run Tests

on: 
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    backend-tests:
        runs-on: ubuntu-latest
        if : github.event.pull_request.draft == false

        steps:
            - uses: actions/checkout@v3

            - name: Install Poetry
              uses: snok/install-poetry@v1
              with:
                version: 1.6.1
            
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: 3.13
                cache: 'poetry'
                
            - name: Install Dependencies
              working-directory: ./backend
              run: poetry install --with dev

            - name: Run Tests
              working-directory: ./backend
              run: pytest -vv --nomigrations -s